create table if not exists public.bike_listings (
  id integer generated by default as identity primary key,
  name text not null,
  images jsonb not null default '[]'::jsonb,
  price integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.bike_listings enable row level security;

grant select on table public.bike_listings to anon;
grant select, insert, update, delete on table public.bike_listings to service_role;

drop policy if exists "Bike listings are public to read" on public.bike_listings;
create policy "Bike listings are public to read"
  on public.bike_listings
  for select
  to anon
  using (true);
